import type { Bookmark } from "./daily";

// Self-contained fake bookmark pile for demo / no-Plus play.
// Mock mode runs entirely client-side: deletes just mutate local state,
// so the roulette works anywhere with no token and no API calls.
export const MOCK_BOOKMARKS: Bookmark[] = [
  {
    id: "m1",
    title: "You Probably Don't Need useEffect",
    url: "https://example.dev/no-useeffect",
    summary: "The 4,000-word article you bookmarked during a refactor and never opened.",
    source: { name: "React Patterns Weekly" },
    readTime: 12,
    bookmarkedAt: "2023-08-14T10:00:00Z",
  },
  {
    id: "m2",
    title: "A Complete Guide to CSS Grid (47 examples)",
    url: "https://example.dev/css-grid-guide",
    summary: "You still use flexbox for everything. Be honest.",
    source: { name: "CSS Tricks" },
    readTime: 22,
    bookmarkedAt: "2022-11-02T10:00:00Z",
  },
  {
    id: "m3",
    title: "Rust for JavaScript Developers",
    url: "https://example.dev/rust-for-js",
    summary: "Bookmarked the week you swore you'd learn Rust. That was a while ago.",
    source: { name: "The Rust Blog" },
    readTime: 18,
    bookmarkedAt: "2023-01-09T10:00:00Z",
  },
  {
    id: "m4",
    title: "How We Cut Our AWS Bill by 90%",
    url: "https://example.dev/aws-bill",
    summary: "Aspirational. Your bill went up 90%.",
    source: { name: "Scaling Stories" },
    readTime: 9,
    bookmarkedAt: "2024-03-21T10:00:00Z",
  },
  {
    id: "m5",
    title: "Monads Explained Simply (Part 1 of 6)",
    url: "https://example.dev/monads-1",
    summary: "You did not read parts 2 through 6.",
    source: { name: "Functional Fridays" },
    readTime: 15,
    bookmarkedAt: "2021-06-30T10:00:00Z",
  },
  {
    id: "m6",
    title: "The 2022 State of JS Survey Results",
    url: "https://example.dev/state-of-js-2022",
    summary: "It is no longer 2022.",
    source: { name: "State of JS" },
    readTime: 11,
    bookmarkedAt: "2022-12-15T10:00:00Z",
  },
  {
    id: "m7",
    title: "Why You Should Write a Compiler",
    url: "https://example.dev/write-a-compiler",
    summary: "You should not, but you bookmarked it anyway.",
    source: { name: "Lambda Logs" },
    readTime: 25,
    bookmarkedAt: "2023-05-18T10:00:00Z",
  },
  {
    id: "m8",
    title: "10 VS Code Extensions That Changed My Life",
    url: "https://example.dev/vscode-extensions",
    summary: "Your life remains unchanged.",
    source: { name: "Editor Enjoyer" },
    readTime: 6,
    bookmarkedAt: "2024-01-04T10:00:00Z",
  },
  {
    id: "m9",
    title: "Understanding the Kubernetes Networking Model",
    url: "https://example.dev/k8s-networking",
    summary: "You deploy to a single VPS. This was never relevant.",
    source: { name: "Cloud Native Notes" },
    readTime: 19,
    bookmarkedAt: "2022-09-27T10:00:00Z",
  },
  {
    id: "m10",
    title: "I Rewrote It in Zig and Here's What Happened",
    url: "https://example.dev/rewrote-in-zig",
    summary: "Nothing happened. You closed the tab.",
    source: { name: "Systems Sunday" },
    readTime: 14,
    bookmarkedAt: "2024-02-11T10:00:00Z",
  },
  {
    id: "m11",
    title: "The Pragmatic Guide to Database Indexing",
    url: "https://example.dev/db-indexing",
    summary: "Genuinely useful. Which is why you'll feel guilty deleting it.",
    source: { name: "Backend Brief" },
    readTime: 16,
    bookmarkedAt: "2023-10-08T10:00:00Z",
  },
  {
    id: "m12",
    title: "Building a Second Brain with Markdown Files",
    url: "https://example.dev/second-brain",
    summary: "Your first brain hasn't opened this in 14 months.",
    source: { name: "Productivity Pidgin" },
    readTime: 8,
    bookmarkedAt: "2023-03-30T10:00:00Z",
  },
];
